version: 0.0
os: linux
files:
  - source: a.txt
    destination: /var/www/html
  - source: b.txt
    destination: /var/www/html
  - source: c.txt
    destination: /var/www/html
  - source: d.txt
    destination: /var/www/html
  - source: .htaccess
    destination: /var/www/html
