version: 0.0
os: linux
files:
  - source: a.txt
    destination: /var/www/html
  - source: b.txt
    destination: /var/www/html
  - source: c.txt
    destination: /var/www/html
  - source: d.txt
    destination: /var/www/html
  - source: /sub/t1.txt
    destination: /var/www/html/sub/
  - source: /sub
    destination: /var/www/html/sub/
  - source: .htaccess
    destination: /var/www/html
